spring:
  profiles:
    active: dev
  application:
    name: demo_mall
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    ###连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        ###连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ###连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ###连接池中的最大空闲连接
        max-idle: 5
        ###连接池中的最小空闲连接
        min-idle: 0

# session配置
server:
  servlet:
    session:
      persistent: true
      timeout: 5000
      cookie:
        http-only: false
    context-path: /xcx
  port: 8080

mybatis:
  type-aliases-package: com.sanbangzi.domain.entity
  mapper-locations: classpath*:mapper/*.xml

mapper:
  mappers:
    - com.sanbangzi.common.utils.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql